/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq;


import com.pdmweb.base.jooq.tables.PdmList;
import com.pdmweb.base.jooq.tables.PdmTable;
import com.pdmweb.base.jooq.tables.PdmTableField;
import com.pdmweb.base.jooq.tables.PdmUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 203984654;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>pdm_list</code>.
     */
    public final PdmList PDM_LIST = com.pdmweb.base.jooq.tables.PdmList.PDM_LIST;

    /**
     * The table <code>pdm_table</code>.
     */
    public final PdmTable PDM_TABLE = com.pdmweb.base.jooq.tables.PdmTable.PDM_TABLE;

    /**
     * The table <code>pdm_table_field</code>.
     */
    public final PdmTableField PDM_TABLE_FIELD = com.pdmweb.base.jooq.tables.PdmTableField.PDM_TABLE_FIELD;

    /**
     * The table <code>pdm_user</code>.
     */
    public final PdmUser PDM_USER = com.pdmweb.base.jooq.tables.PdmUser.PDM_USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            PdmList.PDM_LIST,
            PdmTable.PDM_TABLE,
            PdmTableField.PDM_TABLE_FIELD,
            PdmUser.PDM_USER);
    }
}
