/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq;


import com.pdmweb.base.jooq.tables.PdmTable;
import com.pdmweb.base.jooq.tables.PdmTableField;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_PDM_TABLE_1 = Indexes0.SQLITE_AUTOINDEX_PDM_TABLE_1;
    public static final Index PDM_TABLE_FIELD_FIELD_ID_UINDEX = Indexes0.PDM_TABLE_FIELD_FIELD_ID_UINDEX;
    public static final Index PDM_TABLE_FIELD_TABLE_ID_UINDEX = Indexes0.PDM_TABLE_FIELD_TABLE_ID_UINDEX;
    public static final Index SQLITE_AUTOINDEX_PDM_TABLE_FIELD_1 = Indexes0.SQLITE_AUTOINDEX_PDM_TABLE_FIELD_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_PDM_TABLE_1 = Internal.createIndex("sqlite_autoindex_pdm_table_1", PdmTable.PDM_TABLE, new OrderField[] { PdmTable.PDM_TABLE.TABLE_ID }, true);
        public static Index PDM_TABLE_FIELD_FIELD_ID_UINDEX = Internal.createIndex("pdm_table_field_field_id_uindex", PdmTableField.PDM_TABLE_FIELD, new OrderField[] { PdmTableField.PDM_TABLE_FIELD.FIELD_ID }, true);
        public static Index PDM_TABLE_FIELD_TABLE_ID_UINDEX = Internal.createIndex("pdm_table_field_table_id_uindex", PdmTableField.PDM_TABLE_FIELD, new OrderField[] { PdmTableField.PDM_TABLE_FIELD.TABLE_ID }, true);
        public static Index SQLITE_AUTOINDEX_PDM_TABLE_FIELD_1 = Internal.createIndex("sqlite_autoindex_pdm_table_field_1", PdmTableField.PDM_TABLE_FIELD, new OrderField[] { PdmTableField.PDM_TABLE_FIELD.FIELD_ID }, true);
    }
}
