/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq;


import com.pdmweb.base.jooq.tables.PdmList;
import com.pdmweb.base.jooq.tables.PdmTable;
import com.pdmweb.base.jooq.tables.PdmTableField;
import com.pdmweb.base.jooq.tables.PdmUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pdm_list</code>.
     */
    public static final PdmList PDM_LIST = PdmList.PDM_LIST;

    /**
     * The table <code>pdm_table</code>.
     */
    public static final PdmTable PDM_TABLE = PdmTable.PDM_TABLE;

    /**
     * The table <code>pdm_table_field</code>.
     */
    public static final PdmTableField PDM_TABLE_FIELD = PdmTableField.PDM_TABLE_FIELD;

    /**
     * The table <code>pdm_user</code>.
     */
    public static final PdmUser PDM_USER = PdmUser.PDM_USER;
}
