/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq.tables.records;


import com.pdmweb.base.jooq.tables.PdmList;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdmListRecord extends UpdatableRecordImpl<PdmListRecord> implements Record7<Integer, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = -1390376298;

    /**
     * Setter for <code>pdm_list.pdm_id</code>.
     */
    public void setPdmId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pdm_list.pdm_id</code>.
     */
    public Integer getPdmId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pdm_list.pdm_name</code>.
     */
    public void setPdmName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pdm_list.pdm_name</code>.
     */
    public String getPdmName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pdm_list.pdm_version</code>.
     */
    public void setPdmVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pdm_list.pdm_version</code>.
     */
    public String getPdmVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pdm_list.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pdm_list.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pdm_list.create_time</code>.
     */
    public void setCreateTime(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pdm_list.create_time</code>.
     */
    public String getCreateTime() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pdm_list.pdm_desc</code>.
     */
    public void setPdmDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pdm_list.pdm_desc</code>.
     */
    public String getPdmDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pdm_list.pdm_status</code>.
     */
    public void setPdmStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>pdm_list.pdm_status</code>.
     */
    public Integer getPdmStatus() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PdmList.PDM_LIST.PDM_ID;
    }

    @Override
    public Field<String> field2() {
        return PdmList.PDM_LIST.PDM_NAME;
    }

    @Override
    public Field<String> field3() {
        return PdmList.PDM_LIST.PDM_VERSION;
    }

    @Override
    public Field<String> field4() {
        return PdmList.PDM_LIST.UPDATE_TIME;
    }

    @Override
    public Field<String> field5() {
        return PdmList.PDM_LIST.CREATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return PdmList.PDM_LIST.PDM_DESC;
    }

    @Override
    public Field<Integer> field7() {
        return PdmList.PDM_LIST.PDM_STATUS;
    }

    @Override
    public Integer component1() {
        return getPdmId();
    }

    @Override
    public String component2() {
        return getPdmName();
    }

    @Override
    public String component3() {
        return getPdmVersion();
    }

    @Override
    public String component4() {
        return getUpdateTime();
    }

    @Override
    public String component5() {
        return getCreateTime();
    }

    @Override
    public String component6() {
        return getPdmDesc();
    }

    @Override
    public Integer component7() {
        return getPdmStatus();
    }

    @Override
    public Integer value1() {
        return getPdmId();
    }

    @Override
    public String value2() {
        return getPdmName();
    }

    @Override
    public String value3() {
        return getPdmVersion();
    }

    @Override
    public String value4() {
        return getUpdateTime();
    }

    @Override
    public String value5() {
        return getCreateTime();
    }

    @Override
    public String value6() {
        return getPdmDesc();
    }

    @Override
    public Integer value7() {
        return getPdmStatus();
    }

    @Override
    public PdmListRecord value1(Integer value) {
        setPdmId(value);
        return this;
    }

    @Override
    public PdmListRecord value2(String value) {
        setPdmName(value);
        return this;
    }

    @Override
    public PdmListRecord value3(String value) {
        setPdmVersion(value);
        return this;
    }

    @Override
    public PdmListRecord value4(String value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public PdmListRecord value5(String value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public PdmListRecord value6(String value) {
        setPdmDesc(value);
        return this;
    }

    @Override
    public PdmListRecord value7(Integer value) {
        setPdmStatus(value);
        return this;
    }

    @Override
    public PdmListRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PdmListRecord
     */
    public PdmListRecord() {
        super(PdmList.PDM_LIST);
    }

    /**
     * Create a detached, initialised PdmListRecord
     */
    public PdmListRecord(Integer pdmId, String pdmName, String pdmVersion, String updateTime, String createTime, String pdmDesc, Integer pdmStatus) {
        super(PdmList.PDM_LIST);

        set(0, pdmId);
        set(1, pdmName);
        set(2, pdmVersion);
        set(3, updateTime);
        set(4, createTime);
        set(5, pdmDesc);
        set(6, pdmStatus);
    }
}
