/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq.tables.records;


import com.pdmweb.base.jooq.tables.PdmTable;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdmTableRecord extends UpdatableRecordImpl<PdmTableRecord> implements Record7<Object, Object, String, String, String, String, String> {

    private static final long serialVersionUID = -1262669339;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setTableId(Object value) {
        set(0, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getTableId() {
        return get(0);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setPdmId(Object value) {
        set(1, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getPdmId() {
        return get(1);
    }

    /**
     * Setter for <code>pdm_table.table_code</code>.
     */
    public void setTableCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pdm_table.table_code</code>.
     */
    public String getTableCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pdm_table.table_name</code>.
     */
    public void setTableName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pdm_table.table_name</code>.
     */
    public String getTableName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pdm_table.table_desc</code>.
     */
    public void setTableDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pdm_table.table_desc</code>.
     */
    public String getTableDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pdm_table.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pdm_table.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pdm_table.create_time</code>.
     */
    public void setCreateTime(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pdm_table.create_time</code>.
     */
    public String getCreateTime() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Object> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Object, Object, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Object, Object, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return PdmTable.PDM_TABLE.TABLE_ID;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field2() {
        return PdmTable.PDM_TABLE.PDM_ID;
    }

    @Override
    public Field<String> field3() {
        return PdmTable.PDM_TABLE.TABLE_CODE;
    }

    @Override
    public Field<String> field4() {
        return PdmTable.PDM_TABLE.TABLE_NAME;
    }

    @Override
    public Field<String> field5() {
        return PdmTable.PDM_TABLE.TABLE_DESC;
    }

    @Override
    public Field<String> field6() {
        return PdmTable.PDM_TABLE.UPDATE_TIME;
    }

    @Override
    public Field<String> field7() {
        return PdmTable.PDM_TABLE.CREATE_TIME;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getTableId();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object component2() {
        return getPdmId();
    }

    @Override
    public String component3() {
        return getTableCode();
    }

    @Override
    public String component4() {
        return getTableName();
    }

    @Override
    public String component5() {
        return getTableDesc();
    }

    @Override
    public String component6() {
        return getUpdateTime();
    }

    @Override
    public String component7() {
        return getCreateTime();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getTableId();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object value2() {
        return getPdmId();
    }

    @Override
    public String value3() {
        return getTableCode();
    }

    @Override
    public String value4() {
        return getTableName();
    }

    @Override
    public String value5() {
        return getTableDesc();
    }

    @Override
    public String value6() {
        return getUpdateTime();
    }

    @Override
    public String value7() {
        return getCreateTime();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public PdmTableRecord value1(Object value) {
        setTableId(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public PdmTableRecord value2(Object value) {
        setPdmId(value);
        return this;
    }

    @Override
    public PdmTableRecord value3(String value) {
        setTableCode(value);
        return this;
    }

    @Override
    public PdmTableRecord value4(String value) {
        setTableName(value);
        return this;
    }

    @Override
    public PdmTableRecord value5(String value) {
        setTableDesc(value);
        return this;
    }

    @Override
    public PdmTableRecord value6(String value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public PdmTableRecord value7(String value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public PdmTableRecord values(Object value1, Object value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PdmTableRecord
     */
    public PdmTableRecord() {
        super(PdmTable.PDM_TABLE);
    }

    /**
     * Create a detached, initialised PdmTableRecord
     */
    public PdmTableRecord(Object tableId, Object pdmId, String tableCode, String tableName, String tableDesc, String updateTime, String createTime) {
        super(PdmTable.PDM_TABLE);

        set(0, tableId);
        set(1, pdmId);
        set(2, tableCode);
        set(3, tableName);
        set(4, tableDesc);
        set(5, updateTime);
        set(6, createTime);
    }
}
