/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq.tables.records;


import com.pdmweb.base.jooq.tables.PdmUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdmUserRecord extends UpdatableRecordImpl<PdmUserRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1146782755;

    /**
     * Setter for <code>pdm_user.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pdm_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pdm_user.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pdm_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pdm_user.pass_word</code>.
     */
    public void setPassWord(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pdm_user.pass_word</code>.
     */
    public String getPassWord() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PdmUser.PDM_USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return PdmUser.PDM_USER.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return PdmUser.PDM_USER.PASS_WORD;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getPassWord();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getPassWord();
    }

    @Override
    public PdmUserRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public PdmUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public PdmUserRecord value3(String value) {
        setPassWord(value);
        return this;
    }

    @Override
    public PdmUserRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PdmUserRecord
     */
    public PdmUserRecord() {
        super(PdmUser.PDM_USER);
    }

    /**
     * Create a detached, initialised PdmUserRecord
     */
    public PdmUserRecord(Integer userId, String userName, String passWord) {
        super(PdmUser.PDM_USER);

        set(0, userId);
        set(1, userName);
        set(2, passWord);
    }
}
