/*
 * This file is generated by jOOQ.
 */
package com.pdmweb.base.jooq.tables;


import com.pdmweb.base.jooq.DefaultSchema;
import com.pdmweb.base.jooq.Indexes;
import com.pdmweb.base.jooq.Keys;
import com.pdmweb.base.jooq.tables.records.PdmTableFieldRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdmTableField extends TableImpl<PdmTableFieldRecord> {

    private static final long serialVersionUID = -554859925;

    /**
     * The reference instance of <code>pdm_table_field</code>
     */
    public static final PdmTableField PDM_TABLE_FIELD = new PdmTableField();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PdmTableFieldRecord> getRecordType() {
        return PdmTableFieldRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PdmTableFieldRecord, Object> FIELD_ID = createField(DSL.name("field_id"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"Long\"").nullable(false), this, "");

    /**
     * The column <code>pdm_table_field.field_code</code>.
     */
    public final TableField<PdmTableFieldRecord, String> FIELD_CODE = createField(DSL.name("field_code"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>pdm_table_field.field_type</code>.
     */
    public final TableField<PdmTableFieldRecord, String> FIELD_TYPE = createField(DSL.name("field_type"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pdm_table_field.field_size</code>.
     */
    public final TableField<PdmTableFieldRecord, Integer> FIELD_SIZE = createField(DSL.name("field_size"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>pdm_table_field.field_primary</code>.
     */
    public final TableField<PdmTableFieldRecord, String> FIELD_PRIMARY = createField(DSL.name("field_primary"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pdm_table_field.field_isnull</code>.
     */
    public final TableField<PdmTableFieldRecord, String> FIELD_ISNULL = createField(DSL.name("field_isnull"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pdm_table_field.field_desc</code>.
     */
    public final TableField<PdmTableFieldRecord, String> FIELD_DESC = createField(DSL.name("field_desc"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PdmTableFieldRecord, Object> TABLE_ID = createField(DSL.name("table_id"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"Long\"").nullable(false), this, "");

    /**
     * Create a <code>pdm_table_field</code> table reference
     */
    public PdmTableField() {
        this(DSL.name("pdm_table_field"), null);
    }

    /**
     * Create an aliased <code>pdm_table_field</code> table reference
     */
    public PdmTableField(String alias) {
        this(DSL.name(alias), PDM_TABLE_FIELD);
    }

    /**
     * Create an aliased <code>pdm_table_field</code> table reference
     */
    public PdmTableField(Name alias) {
        this(alias, PDM_TABLE_FIELD);
    }

    private PdmTableField(Name alias, Table<PdmTableFieldRecord> aliased) {
        this(alias, aliased, null);
    }

    private PdmTableField(Name alias, Table<PdmTableFieldRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PdmTableField(Table<O> child, ForeignKey<O, PdmTableFieldRecord> key) {
        super(child, key, PDM_TABLE_FIELD);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PDM_TABLE_FIELD_FIELD_ID_UINDEX, Indexes.PDM_TABLE_FIELD_TABLE_ID_UINDEX, Indexes.SQLITE_AUTOINDEX_PDM_TABLE_FIELD_1);
    }

    @Override
    public UniqueKey<PdmTableFieldRecord> getPrimaryKey() {
        return Keys.PK_PDM_TABLE_FIELD;
    }

    @Override
    public List<UniqueKey<PdmTableFieldRecord>> getKeys() {
        return Arrays.<UniqueKey<PdmTableFieldRecord>>asList(Keys.PK_PDM_TABLE_FIELD);
    }

    @Override
    public PdmTableField as(String alias) {
        return new PdmTableField(DSL.name(alias), this);
    }

    @Override
    public PdmTableField as(Name alias) {
        return new PdmTableField(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PdmTableField rename(String name) {
        return new PdmTableField(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PdmTableField rename(Name name) {
        return new PdmTableField(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Object, String, String, Integer, String, String, String, Object> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
